### ISSUE TITLE
can I record other computer activity with this keylogger ?

### ISSUE THREAD

**Issue by astrakyzr** [djhohnstein/SharpLogger#1]

**Comment by djhohnstein** [comment]
"Other" is pretty nebulous here, but in general if you run the executable under the context of another user it will log that user's keystrokes.

This is _not_ a SYSTEM level hooking to all key-tap events, if that's what you're getting at.

**Comment by astrakyzr** [comment]
for example if I run the code or the exe file in my brother pc, can  I record his activities to my own computer ? if it is possible how can I do that? I mean for example which file should be opened in pc.

**Comment by djhohnstein** [comment]
You should only perform activities with authorization from the party being tested. Remotely accessing a machine is outside the scope of this project. This logs data to a temp file for retrieval later. Clone and build the project for more information on its inner workings.

I'm closing this issue.

**Comment by astrakyzr** [comment]
thank you
