### ISSUE TITLE
Can I set a time for writing into a new logfile?

### ISSUE THREAD

**Issue by chrop202** [djhohnstein/SharpLogger#2]
Is there a way how I can put for all 10 minuten the logged code into a new file?

**Comment by djhohnstein** [comment]
Hey Chropldr,

Currently I don't really maintain this or any of my repositories; however, the WireTap repository will stream output to both the console and a file as it receives input. I recommend you use that project instead if you'd like to see file stream output. 

Currently, there is no "wait ten minutes then write to file," though you could implement this by creating a string buffer with the same contents that's being written to the console and a timer that will write that buffer to a file. I don't plan to implement such functionally as I'm happy with WireTap's implementation found here: https://github.com/djhohnstein/WireTap

Best of luck to you.
